- README.rst
Favors reStructured text over Markdown
> Move readme from md to rst

- CHANGELOG.rst
- src/intergalactic/constants.py
- src/intergalactic/functions.py
- src/intergalactic/matrix.py
- src/intergalactic/model.py
- src/intergalactic/tests/test_functions.py
- Added all Phi components from _Ferrini et al.*,1992, ApJ, 387, 138_
- Refactor integration method to use Newton-Cotes (6th order) everywhere
> Refactor global phi

- .travis.yml
- CHANGELOG.rst
- README.rst
- setup.py
- src/intergalactic/abundances.py
- src/intergalactic/cli.py
- src/intergalactic/dtds.py
- src/intergalactic/functions.py
- src/intergalactic/imfs.py
- src/intergalactic/model.py
- src/intergalactic/sample_input/params.yml
- src/intergalactic/settings.py
- src/intergalactic/tests/test_abundances.py
- src/intergalactic/tests/test_cli.py
- src/intergalactic/tests/test_dtds.py
- src/intergalactic/tests/test_functions.py
- src/intergalactic/tests/test_imfs.py
- src/intergalactic/tests/test_matrix.py
- src/intergalactic/tests/test_model.py
New `m_low` and `m_up` settings for mass limits to IMFs.
IMFs are integrated in `[m_low, m_up]` and normalized to `[0, 1]`
> Normalized IMFs

- .coveragerc
- .travis.yml
- README.rst
- setup.py
This PR adds codecov service for coverage analysis
> Add coverage config

- src/intergalactic/model.py
Keep the integration time step constant in t but using Raitieri et al. functions for stellar mass/age relation.
> New functions for age/mass

- setup.cfg
- setup.py
https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files
> Migrate from setup.py to setup.cfg

- CHANGELOG.rst
- docs/configuration.rst
- docs/index.rst
- src/intergalactic/model.py
- src/intergalactic/sample_input/params.yml
- src/intergalactic/settings.py
- src/intergalactic/tests/test_model.py
This PR adds a setting to switch between having the integration constant on `log(t)` or in `t`
> Integration step setting

- CHANGELOG.rst
- README.rst
- docs/configuration.rst
- docs/credits.rst
- src/intergalactic/dtds.py
- src/intergalactic/sample_input/params.yml
- src/intergalactic/settings.py
- src/intergalactic/tests/test_dtds.py
This PR adds a new available DTD: Castrillo et al. 2020.
> Add DTD from Castrillo et at. (2020)

- .travis.yml
- CHANGELOG.rst
- src/intergalactic/imfs.py
- src/intergalactic/model.py
- src/intergalactic/tests/test_imfs.py
This PR modifies the SN Ia rates multiplying per total number of stars per unit of mass formed.
Re: Greggio parameter `A_ia`
> Account for the number of start per mass unit

- CHANGELOG.rst
- README.rst
- docs/configuration.rst
- docs/credits.rst
- docs/index.rst
- docs/usage.rst
- src/starmatrix/__init__.py
- src/starmatrix/constants.py
- src/starmatrix/functions.py
- src/starmatrix/matrix.py
- src/starmatrix/model.py
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/supernovae.py
- src/starmatrix/tests/test_functions.py
- src/starmatrix/tests/test_matrix.py
- src/starmatrix/tests/test_settings.py
- src/starmatrix/tests/test_supernovae.py
This PR adds a `sn_yields` setting to specify the dataset of SN yield to use.
A new dataset is added from Seitenzahl et al. 2013
> Supernovae yields

- CHANGELOG.rst
- README.rst
- docs/configuration.rst
- docs/credits.rst
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/supernovae.py
- src/starmatrix/tests/test_supernovae.py
This PR adds three datasets of Supernovae yields from models in Leung & Nomoto 2018, ApJ, Vol 861, Issue 2, Id 143.
> Leung-Nomoto SN yields

- README.rst
- docs/configuration.rst
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/supernovae.py
- src/starmatrix/tests/test_supernovae.py
This PR adds yields data from several model/authors:
* Bravo, E. et al., 2019, MNRAS, 482, Issue 4, 4346–4363, two datasets (T3 & T4)
* Gronow, S. et al., 2021, A&A, models with He and Core detonation
* Mori, K. et al, 2018, ApJ, 863:176, models W7 (deflag) and WDD2 (double detonation)
> New Supernovae datasets

- CHANGELOG.rst
- README.rst
- docs/configuration.rst
- docs/credits.rst
- src/starmatrix/__init__.py
- src/starmatrix/dtds.py
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/tests/test_dtds.py
This PR add a new DTD option for Supernovae Ia: `chen` and creates a new minor release
> New DTD from Chen, X. et al. 2021

- README.rst
- docs/configuration.rst
- src/starmatrix/dtds.py
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/tests/test_dtds.py
This PR adds six new DTD options from Laura Greggio 2005 for a variety of SN scenarios:
- Close mass range Double Degenerate (0.4 & 1 Gyrs)
- Wide mass range Double Degenerate (0.4 & 1 Gyrs)
- Single Degenerate with Chandrasekhar mass exploders
- Single Degenerate with sub-Chandrasekhar mass exploders
> DTDs from Greggio models

- src/starmatrix/dtds.py
> Update DTD's normalization rates

- .github/workflows/tests.yml
- setup.cfg
This PR adds 3.10 to the CI matrix
> Test in Python 3.10

- .github/workflows/tests.yml
- setup.cfg
Branch to get Starmatrix Python 3.10 compatible
> Latests Scipy/Python

- README.rst
- docs/configuration.rst
- src/starmatrix/imfs.py
- src/starmatrix/sample_input/params.yml
- src/starmatrix/settings.py
- src/starmatrix/tests/test_imfs.py
This PR adds a new IMF from Kroupa 2001. 
New IMF is similar to Kroupa 2002 but with alpha3 = 2.3
> Add Kroupa 2001 IMF

- README.rst
Some minor fixes to make the references consistent.
> Minor fixes to README

- README.rst
Typing this out to tell you was less work than just doing a pull request :)
> Minor fix to the contribtuion link.

- .github/workflows/tests.yml
- setup.cfg
> Python 3.11
